version: '3.8'

services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./be:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - frontend
      - backend
