name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create SSH directory
      run: mkdir -p ~/.ssh
    
    - name: Store PEM key
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/ec2-key.pem
        chmod 600 ~/.ssh/ec2-key.pem
    
    - name: Add to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} '
          cd /home/ubuntu/diemquynh.fun &&
          git pull origin main &&
          rm -rf .env &&
          IP=${{ secrets.EC2_HOST }} &&
          echo "VITE_API_URL=http://$IP:8000" > .env &&
          docker-compose down &&
          docker-compose up -d --build
        ' 